languageCode = "en"
languageName = "English"
weight = 1
title = "Benjamin Trigona-Harany | jaxartes.net"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006 January 2"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Personal website and writings for Benjamin Trigona-Harany"
  # copyright = "Copy, _right?_ :thinking_face:"
