# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""

# disableImageOptimization = false

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 

[header]
  layout = "basic" # valid options: basic, fixed

[footer]
 # showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  #homepageImage = "IMAGE.jpg" # used in: hero, and card
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false 
  showAuthorsBadges = false 
  showWordCount = false
  showSummary = true
  sharingLinks = [] # [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  #showViews = false
  #showLikes = false
  #showTableOfContents = true
  #cardView = false

[term]
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  #showViews = false
  #showLikes = false
  #showTableOfContents = true
  #groupByYear = false
  #cardViewScreenWidth = false
  #cardView = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
