# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea = false
smartTOC = false
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
 # showMenu = true
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  #homepageImage = "IMAGE.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/pages"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showDateOnlyInArticle = false
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = false
  #Â relatedContentLimit = 3
  showTaxonomies = false 
  showAuthorsBadges = false 
  showWordCount = false
  # sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email"]
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  #showViews = false
  #showLikes = false
  #showTableOfContents = true
  #cardView = false

[term]
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  #showViews = false
  #showLikes = false
  #showTableOfContents = true
  #groupByYear = false
  #cardViewScreenWidth = false
  #cardView = false


[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  websiteid = "52b9571f-487a-45f9-b522-2dda7e579f42"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  google = "rj6pajYYOfdl4MQOUwnweKW_jDonxKfZGbe2O-Fo3c4"
  # bing = ""
  # pinterest = ""
  # yandex = ""

[author]
  name = "Benjamin Trigona-Harany"
  image = "img/author.jpg"
  #headline = ""
  #bio = "A little bit about you"
  links = [
    { link = "https://www.jaxartes.net/" },
    { email = "mailto:info@jaxartes.net" },
    { github = "https://github.com/bosth" },
    { linkedin = "https://linkedin.com/in/benth" },
    { mastodon = "https://mapstodon.space/@jerseybastion" },
    { worldcat = "https://www.worldcat.org/search?q=Benjamin+Trigona+Harany" },
  ]
